# -*- coding: utf-8 -*-
"""Sparse_Matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-EQ4zu19m47aBsFeuezQyjeuza4kYEgl
"""

#A Sparse Marix has a Sparsity Percentage>50% (more than 50% elements are zeroes)

import numpy as np

r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))

print("Enter ",r*c," elements separated by spaces in a single line:")
elements = list(map(int, input().split()))
#using the map and split functions help us take input entered in a single line

#forming an array of the entered elements
matrix=np.array(elements)

#reshaping the array with elements into a matrix
matrix.reshape(r,c)

from scipy.sparse import csr_matrix

#calculating the sparsity percentage using formula [(number of zeroes)/(total number of elements)] * 100
sparse_percentage = (r*c-csr_matrix(matrix).count_nonzero())/(r*c)*100
print("Sparsity Percentage % = ",sparse_percentage)

#CSR or Compressed Sparse Row representation of the sparse matrix
#CSR is the representation of the sparse matrix by three one dimenstional arrays - non zero values, extents of rows and indexes of columns

print(csr_matrix(matrix))